# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/VideoSystem1080p.xdc

# Block Designs: bd/VideoSystem1080p/VideoSystem1080p.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VideoSystem1080p || ORIG_REF_NAME==VideoSystem1080p}]

# IP: bd/VideoSystem1080p/ip/VideoSystem1080p_imageProcess_0_0/VideoSystem1080p_imageProcess_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VideoSystem1080p_imageProcess_0_0 || ORIG_REF_NAME==VideoSystem1080p_imageProcess_0_0}]

# IP: bd/VideoSystem1080p/ip/VideoSystem1080p_imageProcess_0_0/ip/outputBuffer/outputBuffer.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==outputBuffer || ORIG_REF_NAME==outputBuffer}]

# IP: bd/VideoSystem1080p/ip/VideoSystem1080p_imageProcess_0_0/ip/div_gen_0/div_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==div_gen_0 || ORIG_REF_NAME==div_gen_0}]

# IP: bd/VideoSystem1080p/ip/VideoSystem1080p_processing_system7_0_0/VideoSystem1080p_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VideoSystem1080p_processing_system7_0_0 || ORIG_REF_NAME==VideoSystem1080p_processing_system7_0_0}]

# IP: bd/VideoSystem1080p/ip/VideoSystem1080p_axi_dma_0_0/VideoSystem1080p_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VideoSystem1080p_axi_dma_0_0 || ORIG_REF_NAME==VideoSystem1080p_axi_dma_0_0}]

# IP: bd/VideoSystem1080p/ip/VideoSystem1080p_clk_wiz_0_0/VideoSystem1080p_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VideoSystem1080p_clk_wiz_0_0 || ORIG_REF_NAME==VideoSystem1080p_clk_wiz_0_0}]

# IP: bd/VideoSystem1080p/ip/VideoSystem1080p_axi_mem_intercon_0/VideoSystem1080p_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VideoSystem1080p_axi_mem_intercon_0 || ORIG_REF_NAME==VideoSystem1080p_axi_mem_intercon_0}]

# IP: bd/VideoSystem1080p/ip/VideoSystem1080p_rst_processing_system7_0_100M_0/VideoSystem1080p_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VideoSystem1080p_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==VideoSystem1080p_rst_processing_system7_0_100M_0}]

# IP: bd/VideoSystem1080p/ip/VideoSystem1080p_processing_system7_0_axi_periph_0/VideoSystem1080p_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VideoSystem1080p_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==VideoSystem1080p_processing_system7_0_axi_periph_0}]

# IP: bd/VideoSystem1080p/ip/VideoSystem1080p_xbar_0/VideoSystem1080p_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VideoSystem1080p_xbar_0 || ORIG_REF_NAME==VideoSystem1080p_xbar_0}]

# IP: bd/VideoSystem1080p/ip/VideoSystem1080p_axis_dwidth_converter_0_0/VideoSystem1080p_axis_dwidth_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VideoSystem1080p_axis_dwidth_converter_0_0 || ORIG_REF_NAME==VideoSystem1080p_axis_dwidth_converter_0_0}]

# IP: bd/VideoSystem1080p/ip/VideoSystem1080p_v_tc_0_0/VideoSystem1080p_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VideoSystem1080p_v_tc_0_0 || ORIG_REF_NAME==VideoSystem1080p_v_tc_0_0}]

# IP: bd/VideoSystem1080p/ip/VideoSystem1080p_v_axi4s_vid_out_0_0/VideoSystem1080p_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VideoSystem1080p_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==VideoSystem1080p_v_axi4s_vid_out_0_0}]

# IP: bd/VideoSystem1080p/ip/VideoSystem1080p_xlconstant_0_0/VideoSystem1080p_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VideoSystem1080p_xlconstant_0_0 || ORIG_REF_NAME==VideoSystem1080p_xlconstant_0_0}]

# IP: bd/VideoSystem1080p/ip/VideoSystem1080p_axi_vdma_0_0/VideoSystem1080p_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VideoSystem1080p_axi_vdma_0_0 || ORIG_REF_NAME==VideoSystem1080p_axi_vdma_0_0}]

# IP: bd/VideoSystem1080p/ip/VideoSystem1080p_xbar_1/VideoSystem1080p_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VideoSystem1080p_xbar_1 || ORIG_REF_NAME==VideoSystem1080p_xbar_1}]

# IP: bd/VideoSystem1080p/ip/VideoSystem1080p_xlslice_0_0/VideoSystem1080p_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VideoSystem1080p_xlslice_0_0 || ORIG_REF_NAME==VideoSystem1080p_xlslice_0_0}]

# IP: bd/VideoSystem1080p/ip/VideoSystem1080p_mux_0_0/VideoSystem1080p_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VideoSystem1080p_mux_0_0 || ORIG_REF_NAME==VideoSystem1080p_mux_0_0}]

# IP: bd/VideoSystem1080p/ip/VideoSystem1080p_xlslice_0_1/VideoSystem1080p_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VideoSystem1080p_xlslice_0_1 || ORIG_REF_NAME==VideoSystem1080p_xlslice_0_1}]

# IP: bd/VideoSystem1080p/ip/VideoSystem1080p_xlslice_0_2/VideoSystem1080p_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VideoSystem1080p_xlslice_0_2 || ORIG_REF_NAME==VideoSystem1080p_xlslice_0_2}]

# IP: bd/VideoSystem1080p/ip/VideoSystem1080p_xlconcat_0_0/VideoSystem1080p_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VideoSystem1080p_xlconcat_0_0 || ORIG_REF_NAME==VideoSystem1080p_xlconcat_0_0}]

# IP: bd/VideoSystem1080p/ip/VideoSystem1080p_auto_pc_0/VideoSystem1080p_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VideoSystem1080p_auto_pc_0 || ORIG_REF_NAME==VideoSystem1080p_auto_pc_0}]

# IP: bd/VideoSystem1080p/ip/VideoSystem1080p_auto_us_0/VideoSystem1080p_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VideoSystem1080p_auto_us_0 || ORIG_REF_NAME==VideoSystem1080p_auto_us_0}]

# IP: bd/VideoSystem1080p/ip/VideoSystem1080p_auto_us_1/VideoSystem1080p_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VideoSystem1080p_auto_us_1 || ORIG_REF_NAME==VideoSystem1080p_auto_us_1}]

# IP: bd/VideoSystem1080p/ip/VideoSystem1080p_auto_pc_1/VideoSystem1080p_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VideoSystem1080p_auto_pc_1 || ORIG_REF_NAME==VideoSystem1080p_auto_pc_1}]

# XDC: bd/VideoSystem1080p/ip/VideoSystem1080p_imageProcess_0_0/ip/outputBuffer/outputBuffer/outputBuffer.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==outputBuffer || ORIG_REF_NAME==outputBuffer}] {/U0 }]/U0 ]]

# XDC: bd/VideoSystem1080p/ip/VideoSystem1080p_imageProcess_0_0/ip/outputBuffer/outputBuffer_ooc.xdc

# XDC: bd/VideoSystem1080p/ip/VideoSystem1080p_imageProcess_0_0/ip/div_gen_0/div_gen_0_ooc.xdc

# XDC: bd/VideoSystem1080p/ip/VideoSystem1080p_processing_system7_0_0/VideoSystem1080p_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==VideoSystem1080p_processing_system7_0_0 || ORIG_REF_NAME==VideoSystem1080p_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/VideoSystem1080p/ip/VideoSystem1080p_axi_dma_0_0/VideoSystem1080p_axi_dma_0_0_ooc.xdc

# XDC: bd/VideoSystem1080p/ip/VideoSystem1080p_axi_dma_0_0/VideoSystem1080p_axi_dma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==VideoSystem1080p_axi_dma_0_0 || ORIG_REF_NAME==VideoSystem1080p_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/VideoSystem1080p/ip/VideoSystem1080p_axi_dma_0_0/VideoSystem1080p_axi_dma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==VideoSystem1080p_axi_dma_0_0 || ORIG_REF_NAME==VideoSystem1080p_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/VideoSystem1080p/ip/VideoSystem1080p_clk_wiz_0_0/VideoSystem1080p_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==VideoSystem1080p_clk_wiz_0_0 || ORIG_REF_NAME==VideoSystem1080p_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/VideoSystem1080p/ip/VideoSystem1080p_clk_wiz_0_0/VideoSystem1080p_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==VideoSystem1080p_clk_wiz_0_0 || ORIG_REF_NAME==VideoSystem1080p_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/VideoSystem1080p/ip/VideoSystem1080p_clk_wiz_0_0/VideoSystem1080p_clk_wiz_0_0_ooc.xdc

# XDC: bd/VideoSystem1080p/ip/VideoSystem1080p_rst_processing_system7_0_100M_0/VideoSystem1080p_rst_processing_system7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==VideoSystem1080p_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==VideoSystem1080p_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/VideoSystem1080p/ip/VideoSystem1080p_rst_processing_system7_0_100M_0/VideoSystem1080p_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==VideoSystem1080p_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==VideoSystem1080p_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/VideoSystem1080p/ip/VideoSystem1080p_rst_processing_system7_0_100M_0/VideoSystem1080p_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/VideoSystem1080p/ip/VideoSystem1080p_xbar_0/VideoSystem1080p_xbar_0_ooc.xdc

# XDC: bd/VideoSystem1080p/ip/VideoSystem1080p_axis_dwidth_converter_0_0/VideoSystem1080p_axis_dwidth_converter_0_0_ooc.xdc

# XDC: bd/VideoSystem1080p/ip/VideoSystem1080p_v_tc_0_0/VideoSystem1080p_v_tc_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==VideoSystem1080p_v_tc_0_0 || ORIG_REF_NAME==VideoSystem1080p_v_tc_0_0}] {/U0 }]/U0 ]]

# XDC: bd/VideoSystem1080p/ip/VideoSystem1080p_v_tc_0_0/VideoSystem1080p_v_tc_0_0_ooc.xdc

# XDC: bd/VideoSystem1080p/ip/VideoSystem1080p_v_axi4s_vid_out_0_0/VideoSystem1080p_v_axi4s_vid_out_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==VideoSystem1080p_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==VideoSystem1080p_v_axi4s_vid_out_0_0}] {/inst }]/inst ]]

# XDC: bd/VideoSystem1080p/ip/VideoSystem1080p_v_axi4s_vid_out_0_0/VideoSystem1080p_v_axi4s_vid_out_0_0_ooc.xdc

# XDC: bd/VideoSystem1080p/ip/VideoSystem1080p_axi_vdma_0_0/VideoSystem1080p_axi_vdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==VideoSystem1080p_axi_vdma_0_0 || ORIG_REF_NAME==VideoSystem1080p_axi_vdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/VideoSystem1080p/ip/VideoSystem1080p_axi_vdma_0_0/VideoSystem1080p_axi_vdma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==VideoSystem1080p_axi_vdma_0_0 || ORIG_REF_NAME==VideoSystem1080p_axi_vdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/VideoSystem1080p/ip/VideoSystem1080p_axi_vdma_0_0/VideoSystem1080p_axi_vdma_0_0_ooc.xdc

# XDC: bd/VideoSystem1080p/ip/VideoSystem1080p_xbar_1/VideoSystem1080p_xbar_1_ooc.xdc

# XDC: bd/VideoSystem1080p/ip/VideoSystem1080p_auto_pc_0/VideoSystem1080p_auto_pc_0_ooc.xdc

# XDC: bd/VideoSystem1080p/ip/VideoSystem1080p_auto_us_0/VideoSystem1080p_auto_us_0_ooc.xdc

# XDC: bd/VideoSystem1080p/ip/VideoSystem1080p_auto_us_0/VideoSystem1080p_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==VideoSystem1080p_auto_us_0 || ORIG_REF_NAME==VideoSystem1080p_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/VideoSystem1080p/ip/VideoSystem1080p_auto_us_1/VideoSystem1080p_auto_us_1_ooc.xdc

# XDC: bd/VideoSystem1080p/ip/VideoSystem1080p_auto_us_1/VideoSystem1080p_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==VideoSystem1080p_auto_us_1 || ORIG_REF_NAME==VideoSystem1080p_auto_us_1}] {/inst }]/inst ]]

# XDC: bd/VideoSystem1080p/ip/VideoSystem1080p_auto_pc_1/VideoSystem1080p_auto_pc_1_ooc.xdc

# XDC: bd/VideoSystem1080p/VideoSystem1080p_ooc.xdc
