# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.cache/wt [current_project]
set_property parent.project_path C:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths c:/Users/USER/Desktop/IP1080RGB [current_project]
add_files C:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/sources_1/bd/VideoSystem1080p/VideoSystem1080p.bd
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/sources_1/bd/VideoSystem1080p/ip/VideoSystem1080p_imageProcess_0_0/ip/outputBuffer/outputBuffer/outputBuffer.xdc]
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/sources_1/bd/VideoSystem1080p/ip/VideoSystem1080p_imageProcess_0_0/ip/outputBuffer/outputBuffer_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/sources_1/bd/VideoSystem1080p/ip/VideoSystem1080p_imageProcess_0_0/ip/div_gen_0/div_gen_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/sources_1/bd/VideoSystem1080p/ip/VideoSystem1080p_processing_system7_0_0/VideoSystem1080p_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/sources_1/bd/VideoSystem1080p/ip/VideoSystem1080p_axi_dma_0_0/VideoSystem1080p_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/sources_1/bd/VideoSystem1080p/ip/VideoSystem1080p_axi_dma_0_0/VideoSystem1080p_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/sources_1/bd/VideoSystem1080p/ip/VideoSystem1080p_axi_dma_0_0/VideoSystem1080p_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/sources_1/bd/VideoSystem1080p/ip/VideoSystem1080p_clk_wiz_0_0/VideoSystem1080p_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/sources_1/bd/VideoSystem1080p/ip/VideoSystem1080p_clk_wiz_0_0/VideoSystem1080p_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/sources_1/bd/VideoSystem1080p/ip/VideoSystem1080p_clk_wiz_0_0/VideoSystem1080p_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/sources_1/bd/VideoSystem1080p/ip/VideoSystem1080p_rst_processing_system7_0_100M_0/VideoSystem1080p_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/sources_1/bd/VideoSystem1080p/ip/VideoSystem1080p_rst_processing_system7_0_100M_0/VideoSystem1080p_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/sources_1/bd/VideoSystem1080p/ip/VideoSystem1080p_rst_processing_system7_0_100M_0/VideoSystem1080p_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/sources_1/bd/VideoSystem1080p/ip/VideoSystem1080p_xbar_0/VideoSystem1080p_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/sources_1/bd/VideoSystem1080p/ip/VideoSystem1080p_axis_dwidth_converter_0_0/VideoSystem1080p_axis_dwidth_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/sources_1/bd/VideoSystem1080p/ip/VideoSystem1080p_v_tc_0_0/VideoSystem1080p_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/sources_1/bd/VideoSystem1080p/ip/VideoSystem1080p_v_tc_0_0/VideoSystem1080p_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/sources_1/bd/VideoSystem1080p/ip/VideoSystem1080p_v_axi4s_vid_out_0_0/VideoSystem1080p_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/sources_1/bd/VideoSystem1080p/ip/VideoSystem1080p_v_axi4s_vid_out_0_0/VideoSystem1080p_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/sources_1/bd/VideoSystem1080p/ip/VideoSystem1080p_axi_vdma_0_0/VideoSystem1080p_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/sources_1/bd/VideoSystem1080p/ip/VideoSystem1080p_axi_vdma_0_0/VideoSystem1080p_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/sources_1/bd/VideoSystem1080p/ip/VideoSystem1080p_axi_vdma_0_0/VideoSystem1080p_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/sources_1/bd/VideoSystem1080p/ip/VideoSystem1080p_xbar_1/VideoSystem1080p_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/sources_1/bd/VideoSystem1080p/ip/VideoSystem1080p_auto_pc_0/VideoSystem1080p_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/sources_1/bd/VideoSystem1080p/ip/VideoSystem1080p_auto_us_0/VideoSystem1080p_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/sources_1/bd/VideoSystem1080p/ip/VideoSystem1080p_auto_us_0/VideoSystem1080p_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/sources_1/bd/VideoSystem1080p/ip/VideoSystem1080p_auto_us_1/VideoSystem1080p_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/sources_1/bd/VideoSystem1080p/ip/VideoSystem1080p_auto_us_1/VideoSystem1080p_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/sources_1/bd/VideoSystem1080p/ip/VideoSystem1080p_auto_pc_1/VideoSystem1080p_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/sources_1/bd/VideoSystem1080p/VideoSystem1080p_ooc.xdc]
set_property is_locked true [get_files C:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/sources_1/bd/VideoSystem1080p/VideoSystem1080p.bd]

read_verilog -library xil_defaultlib {
  C:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/sources_1/new/mux.v
  C:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/sources_1/bd/VideoSystem1080p/hdl/VideoSystem1080p_wrapper.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/constrs_1/new/VideoSystem1080p.xdc
set_property used_in_implementation false [get_files C:/Users/USER/Desktop/VideoSystem1080p/VideoSystem1080p.srcs/constrs_1/new/VideoSystem1080p.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top VideoSystem1080p_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef VideoSystem1080p_wrapper.dcp

catch { report_utilization -file VideoSystem1080p_wrapper_utilization_synth.rpt -pb VideoSystem1080p_wrapper_utilization_synth.pb }
